# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Pagrindinis
    url: '#hero'
    weight: 10
  - name: Apie
    url: 'authors/admin'
    weight: 20
  - name: Paslaugos
    url: '#skills'
    weight: 21
  - name: Kursai
    url: '/courses'
    weight: 22
    identifier: courses
  - name: Įžanga į R
    url: '/courses/izanga-R/'
    weight: 10
    parent: courses
  - name: Duomenų mokslas su R
    url: '/courses/duomenu-mokslas-R/'
    weight: 10
    parent: courses
  - name: Statistika su R
    url: '/courses/statistika-R/'
    weight: 10
    parent: courses
  - name: Blogas
    url: '#posts'
    weight: 30
  - name: Susisiekti
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
